import os
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"

import streamlit as st
import numpy as np
import cv2
from tensorflow.keras.models import load_model
from PIL import Image

# -----------------------------
# Page Configuration
# -----------------------------
st.set_page_config(
    page_title="Brain Tumor Detection",
    page_icon="🧠",
    layout="centered"
)

# -----------------------------
# Load trained model
# -----------------------------
@st.cache_resource
def load_trained_model():
    return load_model("brain_tumor_resnet50.keras")

model = load_trained_model()

# Class labels (same order as training)
class_labels = ['glioma', 'meningioma', 'notumor', 'pituitary']

# -----------------------------
# Image preprocessing function
# -----------------------------
def preprocess_image(image):
    image = cv2.resize(image, (224, 224))
    image = image.astype(np.float32) / 255.0
    image = np.expand_dims(image, axis=0)  # (1, 224, 224, 3)
    return image

# -----------------------------
# UI
# -----------------------------
st.markdown("<h1 style='text-align: center;'>🧠 Brain Tumor Detection System</h1>", unsafe_allow_html=True)
st.markdown("<p style='text-align: center;'>AI-powered MRI analysis for tumor detection</p>", unsafe_allow_html=True)
st.divider()

st.info("📌 Upload a brain MRI image. The system will first detect whether a tumor exists, and if present, identify its type.")

# Upload image
uploaded_file = st.file_uploader("📤 Upload MRI Image", type=["jpg", "jpeg", "png"])

if uploaded_file is not None:
    # Read and display image
    image = Image.open(uploaded_file).convert("RGB")
    image_np = np.array(image)


    st.image(image, caption="🖼 Uploaded MRI Image", use_column_width=True)

    st.divider()

    if st.button("🔍 Detect Tumor"):
        with st.spinner("Analyzing MRI image..."):
            processed_image = preprocess_image(image_np)
            prediction = model.predict(processed_image)[0]
            predicted_class = np.argmax(prediction)
            confidence = np.max(prediction) * 100
            tumor_type = class_labels[predicted_class]

        st.divider()

        # -----------------------------
        # Detection Result Logic
        # -----------------------------
        if tumor_type == "notumor":
            st.success("✅ **No Brain Tumor Detected**")
            st.write(f"🧪 Confidence: **{confidence:.2f}%**")
            st.info("The MRI scan does not show signs of a brain tumor.")
        else:
            st.error("⚠️ **Brain Tumor Detected**")
            st.write(f"🧬 **Tumor Type:** `{tumor_type.capitalize()}`")
            st.write(f"📊 **Confidence:** `{confidence:.2f}%`")

            st.warning(
                "⚕️ This prediction is generated by an AI model and should be verified by a medical professional."
            )

        # Probability distribution (NEW FEATURE ⭐)
        st.subheader("📈 Prediction Confidence Distribution")
        for i, label in enumerate(class_labels):
            st.progress(float(prediction[i]))
            st.caption(f"{label.capitalize()}: {prediction[i]*100:.2f}%")

# Footer
st.markdown("---")
st.caption("🚀 Academic Project | Computer Vision | Brain Tumor Detection using CNN (ResNet50)")
